force-app/main/default/objects/Base_Station__c/Base_Station__c.object-meta.xml
<CustomObject>
    <label>Base Station</label>
    <nameField>
        <label>Base Station Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Stations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Base_Station__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Broken</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <displayFormat>N-{000}</displayFormat>
        <label>Sensor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor__c/fields/Base_Station__c.field-meta.xml
<CustomField>
    <fullName>Base_Station__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Station</label>
    <referenceTo>Base_Station__c</referenceTo>
    <relationshipLabel>Sensors</relationshipLabel>
    <relationshipName>Sensors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sensor__c/fields/Sensor_model__c.field-meta.xml
<CustomField>
    <fullName>Sensor_model__c</fullName>
    <label>Sensor model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SensorController.cls
public with sharing class SensorController {
    @AuraEnabled(cacheable=true)
    public static String getBaseStationName(Id bsId) {
        String result;
        List<Base_Station__c> baseStations = [SELECT Id, Name FROM Base_Station__c];
        Map<Id, String> baseStationMap = new Map<Id, String>();
        for (Base_Station__c bs : baseStations) {
            baseStationMap.put(bs.Id, bs.Name);
        }
        return baseStationMap.get(bsId);
    }


    @AuraEnabled(cacheable=true)
    public static List<Sensor__c> getSensorData() {
        List<Sensor__c> fullSensorList = [SELECT Sensor_model__c, Status__c, Base_Station__r.Name FROM Sensor__c];
        return fullSensorList;
    }

    @AuraEnabled
    public static List<Sensor__c> getSensors(Integer limitSize, Integer offset) {
        List<Sensor__c> sensorsToView = [SELECT Id,  Status__c, Base_Station__c, Base_Station__r.Name, Sensor_Model__c FROM Sensor__c LIMIT :limitSize OFFSET :offset];
        return sensorsToView;
    }

    @AuraEnabled(cacheable=true)
    public static Integer getSensorCount() {
        Integer sensorCount = [SELECT COUNT() FROM Sensor__c];
        return sensorCount;
    }

    @AuraEnabled
    public static void deleteSensor(Id sensorId) {
        delete [SELECT Id FROM Sensor__c WHERE Id = :sensorId];
    }

    @AuraEnabled(cacheable=true)
    public static Decimal getDefaultRecordsPerPage() {
        Decimal defaultRecords = [SELECT Default_Records_Per_Page__c FROM Pagination_Settings__mdt LIMIT 1].Default_Records_Per_Page__c;
        return defaultRecords;
    }
}